export const DB_RANDOMIZER = 'RANDOMIZER';
export const DB_GAME_EVENTS = 'EVENTS';
export const DB_DRINKING_EVENTS = 'DRINKING_EVENTS';
export const DB_PARTY_ANIMALS = 'PARTY_ANIMALS';
export const DB_GAME_MASTERS = 'GAME_MASTER';
